"""
LoRA Fine-tuning for CatVTON (Mask-Based) - MENA Region Adaptation
====================================================================

Expected dataset structure (VITON-HD format):
    data_root/
        train/
            image/              <- person images  (e.g. 000001_0.jpg)
            cloth/              <- garment images  (e.g. 000001_1.jpg)
            agnostic-mask/      <- cloth-agnostic masks generated by AutoMasker
                                   (same filenames as image/, PNG)
            train_pairs.txt     <- one pair per line: "person.jpg cloth.jpg"
        test/                   <- same layout (optional)

Generate agnostic-masks first:
    python preprocess_agnostic_mask.py --data_root_path <data_root>

Run training:
    python train_lora_modified.py \
        --data_root   /path/to/mena_dataset \
        --base_ckpt   runwayml/stable-diffusion-inpainting \
        --attn_ckpt   zhengchong/CatVTON \
        --output_dir  ./output/lora_mena \
        --lora_rank   16 \
        --lora_alpha  32 \
        --batch_size  2 \
        --num_epochs  20 \
        --lr          1e-4 \
        --mixed_precision bf16
"""

import argparse
import os
from pathlib import Path

import torch
import torch.nn.functional as F
from accelerate import Accelerator
from accelerate.utils import ProjectConfiguration
from diffusers import AutoencoderKL, DDIMScheduler, UNet2DConditionModel
from diffusers.optimization import get_scheduler
from accelerate import load_checkpoint_in_model
from huggingface_hub import snapshot_download
from peft import LoraConfig, get_peft_model
from PIL import Image
from torch.utils.data import DataLoader, Dataset

from model.attn_processor import SkipAttnProcessor
from model.utils import get_trainable_module, init_adapter
from utils import prepare_image, prepare_mask_image, resize_and_crop, resize_and_padding


class VirtualTryOnDataset(Dataset):
    def __init__(self, data_root: str, split: str = "train",
                 height: int = 1024, width: int = 768,
                 cloth_type: str = "overall",
                 pairs: list[tuple[str, str]] | None = None):
        self.data_root = Path(data_root)
        self.height = height
        self.width = width
        self.cloth_type = cloth_type

        if pairs is None:
            pairs_file = self.data_root / split / "train_pairs.txt"
            loaded_pairs: list[tuple[str, str]] = []
            with open(pairs_file) as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) == 2:
                        loaded_pairs.append((parts[0], parts[1]))
            self.pairs = loaded_pairs
        else:
            self.pairs = pairs

        self.image_dir = self.data_root / split / "image"
        self.cloth_dir = self.data_root / split / "cloth"
        self.mask_dir = self.data_root / split / "agnostic-mask"

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        person_name, cloth_name = self.pairs[idx]
        person_img = Image.open(self.image_dir / person_name).convert("RGB")
        cloth_img = Image.open(self.cloth_dir / cloth_name).convert("RGB")

        mask_fname = Path(person_name).stem + ".png"
        mask_img = Image.open(self.mask_dir / mask_fname).convert("L")

        size = (self.width, self.height)
        person_img = resize_and_crop(person_img, size)
        cloth_img = resize_and_padding(cloth_img, size)
        mask_img = resize_and_crop(mask_img, size)

        person_t = prepare_image(person_img)
        cloth_t = prepare_image(cloth_img)
        mask_t = prepare_mask_image(mask_img)

        gt_t = person_t.clone()
        masked_person_t = person_t * (mask_t < 0.5)

        return {
            "gt": gt_t.squeeze(0),
            "masked_person": masked_person_t.squeeze(0),
            "cloth": cloth_t.squeeze(0),
            "mask": mask_t.squeeze(0),
        }


def encode(vae: AutoencoderKL, x: torch.Tensor) -> torch.Tensor:
    latents = vae.encode(x).latent_dist.sample()
    return latents * vae.config.scaling_factor


def load_attn_checkpoint(attn_modules, attn_ckpt: str, version: str = "mix"):
    sub_folder = {
        "mix": "mix-48k-1024",
        "vitonhd": "vitonhd-16k-512",
        "dresscode": "dresscode-16k-512",
    }[version]
    if os.path.exists(attn_ckpt):
        ckpt_path = os.path.join(attn_ckpt, sub_folder, "attention")
    else:
        repo_path = snapshot_download(repo_id=attn_ckpt)
        ckpt_path = os.path.join(repo_path, sub_folder, "attention")
    load_checkpoint_in_model(attn_modules, ckpt_path)
    print(f"Loaded attention checkpoint from: {ckpt_path}")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--data_root", required=True)
    p.add_argument("--base_ckpt", default="runwayml/stable-diffusion-inpainting")
    p.add_argument("--attn_ckpt", default="zhengchong/CatVTON")
    p.add_argument("--attn_ckpt_version", default="mix",
                   choices=["mix", "vitonhd", "dresscode"])
    p.add_argument("--output_dir", default="./output/lora_mena")
    p.add_argument("--cloth_type", default="overall",
                   choices=["upper", "lower", "overall", "inner", "outer"])
    p.add_argument("--height", type=int, default=1024)
    p.add_argument("--width", type=int, default=768)
    p.add_argument("--batch_size", type=int, default=1)
    p.add_argument("--num_epochs", type=int, default=20)
    p.add_argument("--lr", type=float, default=1e-4)
    p.add_argument("--lr_scheduler", type=str, default="constant",
                   choices=["constant", "cosine", "cosine_with_restarts", "linear", "polynomial"])
    p.add_argument("--lr_warmup_steps", type=int, default=0)
    p.add_argument("--lora_rank", type=int, default=16)
    p.add_argument("--lora_alpha", type=int, default=32)
    p.add_argument("--lora_dropout", type=float, default=0.05)
    p.add_argument("--lora_target_modules", type=str, default="to_q,to_k,to_v,to_out.0",
                   help="Comma-separated module names to apply LoRA to (e.g. 'to_q,to_v')")
    p.add_argument("--mixed_precision", default="bf16", choices=["no", "fp16", "bf16"])
    p.add_argument("--save_every", type=int, default=5, help="Save checkpoint every N epochs")
    p.add_argument("--val_split", type=float, default=0.1,
                   help="Fraction of train_pairs to hold out for validation (0 disables val)")
    p.add_argument("--val_seed", type=int, default=42)
    p.add_argument("--eval_every", type=int, default=1,
                   help="Run validation every N epochs (only if val_split > 0)")
    p.add_argument("--early_stop_patience", type=int, default=3,
                   help="Stop if val loss doesn't improve for N evals (0 disables)")
    p.add_argument("--early_stop_min_delta", type=float, default=0.0,
                   help="Minimum val loss improvement to reset patience")
    p.add_argument("--num_workers", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--gradient_accumulation_steps", type=int, default=4,
                   help="Accumulate gradients over N steps (effective batch = batch_size x N)")
    p.add_argument("--no_gradient_checkpointing", action="store_true",
                   help="Disable gradient checkpointing (uses more VRAM, trains faster)")
    return p.parse_args()


def _load_pairs_file(path: Path) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    with open(path) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 2:
                pairs.append((parts[0], parts[1]))
    return pairs


def _split_pairs(pairs: list[tuple[str, str]], val_split: float, seed: int):
    if val_split <= 0:
        return pairs, []
    n = len(pairs)
    n_val = max(1, int(round(n * val_split)))
    g = torch.Generator()
    g.manual_seed(seed)
    perm = torch.randperm(n, generator=g).tolist()
    val_idx = set(perm[:n_val])
    train_pairs = [p for i, p in enumerate(pairs) if i not in val_idx]
    val_pairs = [p for i, p in enumerate(pairs) if i in val_idx]
    return train_pairs, val_pairs


@torch.no_grad()
def _compute_batch_loss(vae: AutoencoderKL, unet, noise_scheduler, batch, weight_dtype: torch.dtype):
    gt = batch["gt"].to(weight_dtype)
    masked_person = batch["masked_person"].to(weight_dtype)
    cloth = batch["cloth"].to(weight_dtype)
    mask = batch["mask"].to(weight_dtype)

    gt_latent = encode(vae, gt)
    masked_latent = encode(vae, masked_person)
    cloth_latent = encode(vae, cloth)

    h, w = gt_latent.shape[-2], gt_latent.shape[-1]
    mask_latent = F.interpolate(mask, size=(h, w), mode="nearest")

    noise = torch.randn_like(gt_latent)
    timesteps = torch.randint(
        0,
        noise_scheduler.config.num_train_timesteps,
        (gt_latent.shape[0],),
        device=gt_latent.device,
    ).long()
    noisy_gt = noise_scheduler.add_noise(gt_latent, noise, timesteps)

    noisy_concat = torch.cat([noisy_gt, cloth_latent], dim=-2)
    mask_concat = torch.cat([mask_latent, torch.zeros_like(mask_latent)], dim=-2)
    masked_concat = torch.cat([masked_latent, cloth_latent], dim=-2)
    unet_input = torch.cat([noisy_concat, mask_concat, masked_concat], dim=1)

    noise_pred = unet(
        unet_input,
        timesteps,
        encoder_hidden_states=None,
        return_dict=False,
    )[0]
    noise_pred_person = noise_pred.split(noise_pred.shape[-2] // 2, dim=-2)[0]
    loss = F.mse_loss(noise_pred_person.float(), noise.float(), reduction="mean")
    return loss


def main():
    args = parse_args()

    project_cfg = ProjectConfiguration(project_dir=args.output_dir)
    accelerator = Accelerator(
        mixed_precision=args.mixed_precision,
        project_config=project_cfg,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
    )

    if accelerator.is_main_process:
        os.makedirs(args.output_dir, exist_ok=True)

    torch.manual_seed(args.seed)
    weight_dtype = {
        "no": torch.float32,
        "fp16": torch.float16,
        "bf16": torch.bfloat16,
    }[args.mixed_precision]

    vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse")
    vae.requires_grad_(False)
    vae.eval()
    vae = vae.to(dtype=weight_dtype)

    noise_scheduler = DDIMScheduler.from_pretrained(args.base_ckpt, subfolder="scheduler")

    unet = UNet2DConditionModel.from_pretrained(args.base_ckpt, subfolder="unet")
    init_adapter(unet, cross_attn_cls=SkipAttnProcessor)
    attn_modules = get_trainable_module(unet, "attention")
    load_attn_checkpoint(attn_modules, args.attn_ckpt, args.attn_ckpt_version)

    target_modules = [m.strip() for m in args.lora_target_modules.split(",") if m.strip()]
    if len(target_modules) == 0:
        raise ValueError("--lora_target_modules must contain at least one module name")

    lora_config = LoraConfig(
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        target_modules=target_modules,
        lora_dropout=args.lora_dropout,
        bias="none",
    )
    unet = get_peft_model(unet, lora_config)
    unet.print_trainable_parameters()

    if not args.no_gradient_checkpointing:
        unet.enable_gradient_checkpointing()
        if accelerator.is_main_process:
            print("Gradient checkpointing: ON  (use --no_gradient_checkpointing to disable)")

    pairs_path = Path(args.data_root) / "train" / "train_pairs.txt"
    all_pairs = _load_pairs_file(pairs_path)
    train_pairs, val_pairs = _split_pairs(all_pairs, args.val_split, args.val_seed)
    if accelerator.is_main_process:
        print(f"Pairs: total={len(all_pairs)}  train={len(train_pairs)}  val={len(val_pairs)}  (val_split={args.val_split})")

    train_dataset = VirtualTryOnDataset(
        data_root=args.data_root,
        split="train",
        height=args.height,
        width=args.width,
        cloth_type=args.cloth_type,
        pairs=train_pairs,
    )
    train_dataloader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
    )

    val_dataloader = None
    if len(val_pairs) > 0:
        val_dataset = VirtualTryOnDataset(
            data_root=args.data_root,
            split="train",
            height=args.height,
            width=args.width,
            cloth_type=args.cloth_type,
            pairs=val_pairs,
        )
        val_dataloader = DataLoader(
            val_dataset,
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=True,
        )

    trainable_params = [p for p in unet.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(trainable_params, lr=args.lr, betas=(0.9, 0.999), weight_decay=1e-2)

    num_update_steps_per_epoch = max(1, len(train_dataloader) // args.gradient_accumulation_steps)
    max_train_steps = args.num_epochs * num_update_steps_per_epoch
    lr_scheduler = get_scheduler(
        name=args.lr_scheduler,
        optimizer=optimizer,
        num_warmup_steps=args.lr_warmup_steps,
        num_training_steps=max_train_steps,
    )

    to_prepare = [unet, vae, optimizer, train_dataloader, lr_scheduler]
    if val_dataloader is not None:
        to_prepare.append(val_dataloader)
    prepared = accelerator.prepare(*to_prepare)
    if val_dataloader is not None:
        unet, vae, optimizer, train_dataloader, lr_scheduler, val_dataloader = prepared
    else:
        unet, vae, optimizer, train_dataloader, lr_scheduler = prepared

    best_val = float("inf")
    no_improve = 0
    for epoch in range(args.num_epochs):
        unet.train()
        epoch_loss = 0.0

        for step, batch in enumerate(train_dataloader):
            with accelerator.accumulate(unet):
                loss = _compute_batch_loss(vae, unet, noise_scheduler, batch, weight_dtype)

            accelerator.backward(loss)
            if accelerator.sync_gradients:
                accelerator.clip_grad_norm_(trainable_params, 1.0)
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()

            epoch_loss += loss.item()
            if accelerator.is_main_process and step % 50 == 0:
                avg = epoch_loss / (step + 1)
                lr = lr_scheduler.get_last_lr()[0] if hasattr(lr_scheduler, "get_last_lr") else args.lr
                print(f"Epoch {epoch+1}/{args.num_epochs}  step {step}  loss {avg:.4f}  lr {lr:.2e}")

        did_eval = False
        if val_dataloader is not None and args.eval_every > 0 and ((epoch + 1) % args.eval_every == 0):
            did_eval = True
            unet.eval()
            val_sum = 0.0
            val_n = 0
            for batch in val_dataloader:
                vloss = _compute_batch_loss(vae, unet, noise_scheduler, batch, weight_dtype)
                bs = batch["gt"].shape[0]
                stats = torch.tensor([vloss.detach().float() * bs, bs], device=vloss.device)
                stats = accelerator.gather_for_metrics(stats)
                val_sum += stats[:, 0].sum().item()
                val_n += int(stats[:, 1].sum().item())
            val_loss = val_sum / max(1, val_n)
            if accelerator.is_main_process:
                print(f"Epoch {epoch+1}/{args.num_epochs}  val_loss {val_loss:.6f}")

            improved = (best_val - val_loss) > args.early_stop_min_delta
            if improved:
                best_val = val_loss
                no_improve = 0
                if accelerator.is_main_process:
                    best_dir = os.path.join(args.output_dir, "best")
                    os.makedirs(best_dir, exist_ok=True)
                    unwrapped = accelerator.unwrap_model(unet)
                    unwrapped.save_pretrained(best_dir)
                    print(f"Saved best checkpoint: {best_dir}  (val_loss={best_val:.6f})")
            else:
                no_improve += 1

        if accelerator.is_main_process and (epoch + 1) % args.save_every == 0:
            save_dir = os.path.join(args.output_dir, f"epoch_{epoch+1:04d}")
            os.makedirs(save_dir, exist_ok=True)
            unwrapped = accelerator.unwrap_model(unet)
            unwrapped.save_pretrained(save_dir)
            print(f"Saved checkpoint: {save_dir}")

        if did_eval and args.early_stop_patience > 0 and no_improve >= args.early_stop_patience:
            if accelerator.is_main_process:
                print(
                    f"Early stopping at epoch {epoch+1}: "
                    f"no val improvement for {no_improve} evals (best_val={best_val:.6f})"
                )
            break

    if accelerator.is_main_process:
        final_dir = os.path.join(args.output_dir, "final")
        os.makedirs(final_dir, exist_ok=True)
        unwrapped = accelerator.unwrap_model(unet)
        unwrapped.save_pretrained(final_dir)
        print(f"Training complete. Final model saved to: {final_dir}")


if __name__ == "__main__":
    main()
