"""
LoRA Fine-tuning for CatVTON (Mask-Based) – MENA Region Adaptation
====================================================================

Expected dataset structure (VITON-HD format):
    data_root/
        train/
            image/              <- person images  (e.g. 000001_0.jpg)
            cloth/              <- garment images  (e.g. 000001_1.jpg)
            agnostic-mask/      <- cloth-agnostic masks generated by AutoMasker
                                   (same filenames as image/, PNG)
            train_pairs.txt     <- one pair per line: "person.jpg cloth.jpg"
        test/                   <- same layout (optional)

Generate agnostic-masks first:
    python preprocess_agnostic_mask.py --data_root_path <data_root>

Run training:
    python train_lora.py \
        --data_root   /path/to/mena_dataset \
        --base_ckpt   runwayml/stable-diffusion-inpainting \
        --attn_ckpt   zhengchong/CatVTON \
        --output_dir  ./output/lora_mena \
        --lora_rank   16 \
        --lora_alpha  32 \
        --batch_size  2 \
        --num_epochs  20 \
        --lr          1e-4 \
        --mixed_precision bf16
"""

import argparse
import os
from pathlib import Path

import torch
import torch.nn.functional as F
from accelerate import Accelerator
from accelerate.utils import ProjectConfiguration
from diffusers import AutoencoderKL, DDIMScheduler, UNet2DConditionModel
from diffusers.utils.torch_utils import randn_tensor
from accelerate import load_checkpoint_in_model
from huggingface_hub import snapshot_download
from peft import LoraConfig, get_peft_model
from PIL import Image
from torch.utils.data import DataLoader, Dataset

from model.attn_processor import SkipAttnProcessor
from model.utils import get_trainable_module, init_adapter
from utils import prepare_image, prepare_mask_image, resize_and_crop, resize_and_padding


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class VirtualTryOnDataset(Dataset):
    """
    VITON-HD–format dataset for virtual try-on fine-tuning.

    The ground-truth (GT) image is the person image itself: the model learns
    to reconstruct the GT from a masked person + cloth condition, so after
    training on MENA garments it will know how those garments drape and look.
    """

    def __init__(self, data_root: str, split: str = "train",
                 height: int = 1024, width: int = 768,
                 cloth_type: str = "overall"):
        self.data_root = Path(data_root)
        self.height = height
        self.width = width
        self.cloth_type = cloth_type

        pairs_file = self.data_root / split / "train_pairs.txt"
        self.pairs = []
        with open(pairs_file) as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) == 2:
                    self.pairs.append((parts[0], parts[1]))

        self.image_dir = self.data_root / split / "image"
        self.cloth_dir = self.data_root / split / "cloth"
        self.mask_dir  = self.data_root / split / "agnostic-mask"

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        person_name, cloth_name = self.pairs[idx]

        # ── load ──────────────────────────────────────────────────────────
        person_img = Image.open(self.image_dir / person_name).convert("RGB")
        cloth_img  = Image.open(self.cloth_dir  / cloth_name).convert("RGB")

        # mask filename matches person filename with .png extension
        mask_fname = Path(person_name).stem + ".png"
        mask_img   = Image.open(self.mask_dir / mask_fname).convert("L")

        # ── resize ────────────────────────────────────────────────────────
        size = (self.width, self.height)
        person_img = resize_and_crop(person_img, size)
        cloth_img  = resize_and_padding(cloth_img, size)
        mask_img   = resize_and_crop(mask_img, size)

        # ── to tensor ────────────────────────────────────────────────────
        person_t = prepare_image(person_img)        # [1, 3, H, W]  ∈ [-1, 1]
        cloth_t  = prepare_image(cloth_img)         # [1, 3, H, W]  ∈ [-1, 1]
        mask_t   = prepare_mask_image(mask_img)     # [1, 1, H, W]  ∈ {0, 1}

        # GT = full person image (what we want to reconstruct)
        gt_t = person_t.clone()

        # Masked person = person with garment region zeroed out (condition)
        masked_person_t = person_t * (mask_t < 0.5)

        return {
            "gt":            gt_t.squeeze(0),             # [3, H, W]
            "masked_person": masked_person_t.squeeze(0),  # [3, H, W]
            "cloth":         cloth_t.squeeze(0),          # [3, H, W]
            "mask":          mask_t.squeeze(0),           # [1, H, W]
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def encode(vae: AutoencoderKL, x: torch.Tensor) -> torch.Tensor:
    """VAE-encode a batch; returns scaled latents."""
    latents = vae.encode(x).latent_dist.sample()
    return latents * vae.config.scaling_factor


def load_attn_checkpoint(attn_modules, attn_ckpt: str, version: str = "mix"):
    sub_folder = {
        "mix":        "mix-48k-1024",
        "vitonhd":    "vitonhd-16k-512",
        "dresscode":  "dresscode-16k-512",
    }[version]
    if os.path.exists(attn_ckpt):
        ckpt_path = os.path.join(attn_ckpt, sub_folder, "attention")
    else:
        repo_path = snapshot_download(repo_id=attn_ckpt)
        ckpt_path = os.path.join(repo_path, sub_folder, "attention")
    load_checkpoint_in_model(attn_modules, ckpt_path)
    print(f"Loaded attention checkpoint from: {ckpt_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--data_root",       required=True)
    p.add_argument("--base_ckpt",       default="runwayml/stable-diffusion-inpainting")
    p.add_argument("--attn_ckpt",       default="zhengchong/CatVTON")
    p.add_argument("--attn_ckpt_version", default="mix",
                   choices=["mix", "vitonhd", "dresscode"])
    p.add_argument("--output_dir",      default="./output/lora_mena")
    p.add_argument("--cloth_type",      default="overall",
                   choices=["upper", "lower", "overall", "inner", "outer"])
    p.add_argument("--height",          type=int, default=1024)
    p.add_argument("--width",           type=int, default=768)
    p.add_argument("--batch_size",      type=int, default=1)
    p.add_argument("--num_epochs",      type=int, default=20)
    p.add_argument("--lr",              type=float, default=1e-4)
    p.add_argument("--lora_rank",       type=int, default=16)
    p.add_argument("--lora_alpha",      type=int, default=32)
    p.add_argument("--lora_dropout",    type=float, default=0.05)
    p.add_argument("--mixed_precision", default="bf16",
                   choices=["no", "fp16", "bf16"])
    p.add_argument("--save_every",      type=int, default=5,
                   help="Save checkpoint every N epochs")
    p.add_argument("--num_workers",     type=int, default=4)
    p.add_argument("--seed",            type=int, default=42)
    p.add_argument("--gradient_accumulation_steps", type=int, default=4,
                   help="Accumulate gradients over N steps (effective batch = batch_size × N)")
    p.add_argument("--no_gradient_checkpointing", action="store_true",
                   help="Disable gradient checkpointing (uses more VRAM, trains faster)")
    return p.parse_args()


def main():
    args = parse_args()

    # ── Accelerator ───────────────────────────────────────────────────────
    project_cfg = ProjectConfiguration(project_dir=args.output_dir)
    accelerator = Accelerator(
        mixed_precision=args.mixed_precision,
        project_config=project_cfg,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
    )

    if accelerator.is_main_process:
        os.makedirs(args.output_dir, exist_ok=True)

    torch.manual_seed(args.seed)
    weight_dtype = {
        "no":   torch.float32,
        "fp16": torch.float16,
        "bf16": torch.bfloat16,
    }[args.mixed_precision]

    # ── Load frozen components ─────────────────────────────────────────────
    vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse")
    vae.requires_grad_(False)
    vae.eval()

    noise_scheduler = DDIMScheduler.from_pretrained(
        args.base_ckpt, subfolder="scheduler"
    )

    # ── Load UNet & install CatVTON attention adapters ────────────────────
    unet = UNet2DConditionModel.from_pretrained(args.base_ckpt, subfolder="unet")

    # Replace cross-attention with SkipAttnProcessor (CatVTON design)
    init_adapter(unet, cross_attn_cls=SkipAttnProcessor)
    attn_modules = get_trainable_module(unet, "attention")

    # Load pre-trained CatVTON attention weights
    load_attn_checkpoint(attn_modules, args.attn_ckpt, args.attn_ckpt_version)

    # ── Apply LoRA ────────────────────────────────────────────────────────
    # Target the linear projections inside every self-attention block.
    # This adapts the model to MENA garment textures and draping patterns
    # while keeping the vast majority of parameters frozen.
    lora_config = LoraConfig(
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        target_modules=["to_q", "to_k", "to_v", "to_out.0"],
        lora_dropout=args.lora_dropout,
        bias="none",
    )
    unet = get_peft_model(unet, lora_config)
    unet.print_trainable_parameters()

    # Gradient checkpointing: recomputes activations during backward pass
    # instead of storing them. Saves ~40% VRAM at the cost of ~30% more compute.
    # MANDATORY at 1024×768 on anything under 40 GB VRAM.
    if not args.no_gradient_checkpointing:
        unet.enable_gradient_checkpointing()
        if accelerator.is_main_process:
            print("Gradient checkpointing: ON  (use --no_gradient_checkpointing to disable)")

    # ── Dataset & DataLoader ──────────────────────────────────────────────
    dataset = VirtualTryOnDataset(
        data_root=args.data_root,
        split="train",
        height=args.height,
        width=args.width,
        cloth_type=args.cloth_type,
    )
    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
    )

    # ── Optimizer (LoRA params only) ──────────────────────────────────────
    trainable_params = [p for p in unet.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(trainable_params, lr=args.lr,
                                  betas=(0.9, 0.999), weight_decay=1e-2)

    # ── Prepare with Accelerator ──────────────────────────────────────────
    unet, vae, optimizer, dataloader = accelerator.prepare(
        unet, vae, optimizer, dataloader
    )

    # ── Training loop ─────────────────────────────────────────────────────
    for epoch in range(args.num_epochs):
        unet.train()
        epoch_loss = 0.0

        for step, batch in enumerate(dataloader):
            with accelerator.accumulate(unet):
                gt            = batch["gt"].to(weight_dtype)            # [B, 3, H, W]
                masked_person = batch["masked_person"].to(weight_dtype) # [B, 3, H, W]
                cloth         = batch["cloth"].to(weight_dtype)         # [B, 3, H, W]
                mask          = batch["mask"].to(weight_dtype)          # [B, 1, H, W]

                with torch.no_grad():
                    # Encode everything to latent space
                    gt_latent     = encode(vae, gt)              # [B, 4, h, w]
                    masked_latent = encode(vae, masked_person)   # [B, 4, h, w]
                    cloth_latent  = encode(vae, cloth)           # [B, 4, h, w]

                    # Downscale mask to latent spatial size
                    h, w = gt_latent.shape[-2], gt_latent.shape[-1]
                    mask_latent = F.interpolate(mask, size=(h, w), mode="nearest")
                    # [B, 1, h, w]

                # ── Add noise ONLY to GT latent (person region) ─────────
                noise     = torch.randn_like(gt_latent)
                timesteps = torch.randint(
                    0,
                    noise_scheduler.config.num_train_timesteps,
                    (gt_latent.shape[0],),
                    device=gt_latent.device,
                ).long()
                noisy_gt = noise_scheduler.add_noise(gt_latent, noise, timesteps)

                # ── Spatial concatenation along height (Y-axis) ─────────
                # Mirrors exactly what happens in CatVTONPipeline.__call__
                noisy_concat  = torch.cat([noisy_gt,     cloth_latent], dim=-2)   # [B, 4, 2h, w]
                mask_concat   = torch.cat([mask_latent,  torch.zeros_like(mask_latent)], dim=-2)  # [B, 1, 2h, w]
                masked_concat = torch.cat([masked_latent, cloth_latent], dim=-2)  # [B, 4, 2h, w]

                # ── UNet input (9 channels) ──────────────────────────────
                # Matches SD-inpainting UNet: [noisy | mask | masked_image]
                unet_input = torch.cat([noisy_concat, mask_concat, masked_concat], dim=1)
                # [B, 9, 2h, w]

                # ── Forward pass ─────────────────────────────────────────
                noise_pred = unet(
                    unet_input,
                    timesteps,
                    encoder_hidden_states=None,
                    return_dict=False,
                )[0]
                # [B, 4, 2h, w]

                # ── Loss only on person (top half) ───────────────────────
                # The cloth half is a fixed condition — we do not supervise it.
                noise_pred_person = noise_pred.split(noise_pred.shape[-2] // 2, dim=-2)[0]
                # [B, 4, h, w]

                loss = F.mse_loss(noise_pred_person.float(), noise.float())

            accelerator.backward(loss)
            if accelerator.sync_gradients:
                accelerator.clip_grad_norm_(trainable_params, 1.0)
            optimizer.step()
            optimizer.zero_grad()

            epoch_loss += loss.item()

            if accelerator.is_main_process and step % 50 == 0:
                avg = epoch_loss / (step + 1)
                print(f"Epoch {epoch+1}/{args.num_epochs}  step {step}  loss {avg:.4f}")

        # ── Checkpoint ────────────────────────────────────────────────────
        if accelerator.is_main_process and (epoch + 1) % args.save_every == 0:
            save_dir = os.path.join(args.output_dir, f"epoch_{epoch+1:04d}")
            os.makedirs(save_dir, exist_ok=True)
            unwrapped = accelerator.unwrap_model(unet)
            unwrapped.save_pretrained(save_dir)
            print(f"Saved checkpoint: {save_dir}")

    # ── Final save ────────────────────────────────────────────────────────
    if accelerator.is_main_process:
        final_dir = os.path.join(args.output_dir, "final")
        os.makedirs(final_dir, exist_ok=True)
        unwrapped = accelerator.unwrap_model(unet)
        unwrapped.save_pretrained(final_dir)
        print(f"Training complete. Final model saved to: {final_dir}")


if __name__ == "__main__":
    main()
